apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./istio/system
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: istio-version
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
    - name: istio-ingress
  interval: 10m0s
  path: ./istio/gateway
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
